### ISSUE TITLE
Missing connector class?

### ISSUE THREAD

**Issue by devstifeev** [bigassforce/aws-sdk#15]
Hi team,

This looks great - thank you! However when I am trying to deploy this to my dev org I am getting the following errors

Am deploying using the "Deploy to Salesforce" button
![connector-missing](https://user-images.githubusercontent.com/17485672/53617212-526aa000-3c3a-11e9-8826-27afe0c8a6e3.png)

Deployment Started
Status: Queued 
Status: Completed 
Deployment Complete
Failures:
classes/Ec2.cls(19,5):Invalid type: Connector
classes/S3.cls(286,38):Variable does not exist: connector
classes/S3Test.cls(62,17):Invalid type: Connector
classes/S3Test.cls(84,17):Invalid type: Connector
classes/S3Test.cls(104,17):Invalid type: Connector
classes/S3Test.cls(158,17):Invalid type: Connector
classes/S3Test.cls(194,17):Invalid type: Connector
classes/S3Test.cls(214,17):Invalid type: Connector
classes/S3Test.cls(223,9):Invalid type: Connector
classes/S3Test.cls(224,9):Variable does not exist: connector
classes/S3Test.cls(227,31):Variable does not exist: connector
classes/Sns.cls(45,5):Invalid type: Connector
classes/S3.cls(264,51):Variable does not exist: connector
classes/S3.cls(20,25):Invalid type: Connector
classes/S3.cls(22,34):Variable does not exist: connector
classes/S3.cls(23,14):Variable does not exist: connector
classes/S3.cls(247,51):Variable does not exist: connector
classes/S3.cls(249,38):Variable does not exist: connector
classes/S3.cls(267,45):Variable does not exist: connector
classes/Ec2.cls(20,26):Invalid type: Connector
classes/Ec2.cls(22,34):Variable does not exist: connector
classes/Ec2.cls(23,14):Variable does not exist: connector
classes/Ec2.cls(398,52):Variable does not exist: connector
classes/Ec2.cls(400,38):Variable does not exist: connector
classes/Ec2.cls(423,52):Variable does not exist: connector
classes/Ec2.cls(425,38):Variable does not exist: connector
classes/Ec2.cls(448,52):Variable does not exist: connector
classes/Ec2.cls(450,38):Variable does not exist: connector
classes/Ec2.cls(469,52):Variable does not exist: connector
classes/Ec2.cls(471,38):Variable does not exist: connector
classes/Ec2Test.cls(160,9):Invalid type: Connector
classes/Ec2Test.cls(309,9):Invalid type: Connector
classes/Ec2Test.cls(444,9):Invalid type: Connector
classes/Ec2Test.cls(543,9):Invalid type: Connector
classes/S3.cls(50,9):Invalid type: Connector
classes/S3.cls(51,26):Invalid type: Connector
classes/S3.cls(69,71):Variable does not exist: conn
classes/S3.cls(76,42):Variable does not exist: conn
classes/S3.cls(102,55):Variable does not exist: conn
classes/S3.cls(102,107):Variable does not exist: Connector
classes/S3.cls(103,42):Variable does not exist: conn
classes/S3.cls(119,55):Variable does not exist: conn
classes/S3.cls(119,107):Variable does not exist: Connector
classes/S3.cls(120,42):Variable does not exist: conn
classes/S3.cls(175,55):Variable does not exist: bucket.conn
classes/S3.cls(177,25):Variable does not exist: bucket.conn
classes/S3.cls(19,5):Invalid type: Connector
classes/SnsTest.cls(77,22):Invalid type: Connector
classes/Sns.cls(46,26):Invalid type: Connector
classes/Sns.cls(48,34):Variable does not exist: connector
classes/Sns.cls(49,14):Variable does not exist: connector
classes/Sns.cls(56,52):Variable does not exist: connector
classes/Sns.cls(79,38):Variable does not exist: connector
classes/SnsTest.cls(6,19):Invalid type: Connector
classes/SnsTest.cls(19,19):Invalid type: Connector
classes/SnsTest.cls(80,9):Invalid type: Connector
classes/SnsTest.cls(81,9):Variable does not exist: connector
classes/SnsTest.cls(82,9):Variable does not exist: connector
classes/SnsTest.cls(83,9):Variable does not exist: connector
classes/SnsTest.cls(106,13):Method does not exist or incorrect signature: void connector() from the type SnsTest
classes/S3.cls(271,38):Variable does not exist: connector
classes/S3.cls(285,51):Variable does not exist: connector

**Comment by bigassforce** [comment]
![Screen Shot 2019-03-08 at 20 39 34](https://user-images.githubusercontent.com/6777144/54054527-50788200-41e2-11e9-938f-4ba26889dd80.png)

**Comment by dculebras** [comment]
Hi Team

I have the same issue like Daniel. The Connector class is missing.

Can you push It?

Tnx
