### ISSUE TITLE
File names with spaces creates problem

### ISSUE THREAD

**Issue by murat-berk** [bigassforce/aws-sdk#2]
First thanks for all the heavy lifting for handling signing files in s3.
This worked great in testing and we start integrating it into our product to download files from S3.

This following fragment fails when fileKey contains spaces. (The error code is HTTP Version not supported, StatusCode=505])
When I try to fix the space in the file name by encoding, we get Forbidden errors.

Could not find a way around this. 
Could you help with this?

				AWS_S3.Bucket bucket = new AWS_Connector(accessAlias).s3(regionName).bucket(bucketName);

				AWS_S3.Content content = bucket.content(fileKey);
				HttpRequest contentRequest = content.presign();
				Http http = new Http();
				HTTPResponse contentResponse = http.send(contentRequest);

We added this 2 methods to handle creating content resources.

        public Content content(String key) {
            return new Content(this, key);
        }

        * Added by ITinvolve to make sure listed contents returns valid presign url
         */
        Content(Bucket bucket, Content content) {
            this.Key = content.Key;
            this.LastModified = content.LastModified;
            this.ETag = content.ETag;
            this.Size = content.Size;
            this.StorageClass = content.StorageClass;
            this.Owner = content.Owner;
            this.bucket = bucket;
        }

**Comment by bigassforce** [comment]
Thanks @murat-berk 

Using this code...

```
String key = 'lat est.txt';
Blob data = Blob.valueOf('test');
Map<String,String> headers = new Map<String,String>{'Content-Type' => 'text/plain'};
HttpResponse response = bucket.createContent(key, headers, data);
```

...was able to reproduce the error:

```
Line: 115, Column: 1
AwsSdk.S3.ClientException: 
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>HttpVersionNotSupported</Code>
    <Message>The HTTP version specified is not supported.</Message>
    <RequestId>2630E0014C32222E</RequestId>
    <HostId>SDGE4yijlvc/lEF1+XJPZ2Bnz5mp5wGinUsJuSEkqtULzodhcYDGh4N22/caWTJuwgyTYpBnWCyoM3myaYntG7L9X51K54CI</HostId>
</Error>
```

**Comment by bigassforce** [comment]
Merhaba @murat-berk, the request signing method has been [adjusted](https://github.com/bigassforce/aws-sdk/commit/3674c7ff14125f8e27f18b635324cbb4009465b8) - just pass the unencoded key when creating and retrieving objects and it seems to behave better now :) best rgds

**Comment by murat-berk** [comment]
This update worked for spaces, but if file name contains # character, or ? character (maybe others), we cannot retrieve object. we are getting file not found errors.
Test 1.png works, test#.png does not work for example as file names.
Any help is appreciated.
