### ISSUE TITLE
SNS class ever converts object in a JSON

### ISSUE THREAD

**Issue by landrady** [bigassforce/aws-sdk#23]
The SNS ever converts the message in a json before notifying. In my case I am using base64 to encode before send the message, but when my other system get this message is a double quote there.

I don't know about the solution, but maybe a serializer class may be used as parameter, so if somebody wants a JsonSerializer is just define it as a delegate.

**Comment by bigassforce** [comment]
Publish class now uses String message, you can encode if needed:
- https://github.com/bigassforce/aws-sdk/blob/master/SNS.cls#L760-L791
