### ISSUE TITLE
Type is not visible: AwsSdk.S3.Content

### ISSUE THREAD

**Issue by aralele** [bigassforce/aws-sdk#6]
I have install the package and once I paste:
AwsSdk.S3.Content content = connector.s3(region).bucket(bucketname).content(filename);
I got the 'not visible' error.

please advice 
Thanks:)

![aws_errror](https://user-images.githubusercontent.com/9461793/49700321-beaea800-fbe5-11e8-9412-44a41fb473ed.png)

**Comment by bigassforce** [comment]
Thanks! Fixed in latest version -- package upgrade link here:
https://github.com/bigassforce/aws-sdk#amazon-web-services-sdk-for-salesforce-apex
