### ISSUE TITLE
The e bucket you are attempting to access must be addressed using the specified endpoint.

### ISSUE THREAD

**Issue by aralele** [bigassforce/aws-sdk#8]
Hi. 
I'm getting 'The bucket you are attempting to access must be addressed using the specified endpoint.' when calling to GET request.

Saw this issue in few post which recommend to switch the 
https://s3.amazonaws.com/salesforcecolony/colony_raw_data.csv TO https://s3-eu-west-1.amazonaws.com/salesforcecolony/colony_raw_data.csv

Thant cause to additional error: 'The request signature we calculated does not match the signature you provided.'

Can you please advice?
I fail login :(

Thanks.
Aharon

**Comment by bigassforce** [comment]
Signature and endpoint fixed in https://github.com/bigassforce/aws-sdk/commit/6845b1d5b741215883a3cbedc9fc07566af10e15
