### ISSUE TITLE
S3 - Request is not yet valid

### ISSUE THREAD

**Issue by Oliviergg** [bigassforce/aws-sdk#9]
Hi,
There is an error in formatting date in connector.cls.
The program is using YYYY to access Year. 
YYYY is code for the weekly calendar
You need to use yyyy instead.
Today (20181231) is the last day of 2018, but we are in the first week of 2019.

So
system.debug(Datetime.now().('YYYY')); => 2019 // Bad Year
system.debug(Datetime.now().('yyyy')); => 2018 

https://github.com/bigassforce/aws-sdk/blob/b3f6a1b61ceaabdabd939da0ff723f644ad326b5/src/classes/Connector.cls#L52

**Comment by bigassforce** [comment]
Fixed in 205c1dc39d4c96d9ced2e91e557fe14e29d24212 by @nbrown30
